=== LennartC/CQ2-Sim/src/main/java/be/lacerta/cq2/battlecalc/util/xml/crits.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="creatures">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="creature" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
		<xs:key name="key">
			<xs:selector xpath="creature"/>
			<xs:field xpath="name"/>
		</xs:key>
	</xs:element>
	<xs:element name="creature">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
				<xs:element ref="class"/>
				<xs:element ref="race" minOccurs="0"/>
				<xs:element ref="damage"/>
				<xs:element ref="health"/>
				<xs:element ref="skill" minOccurs="0"/>
				<xs:element ref="FD"/>
				<xs:element ref="DD"/>
				<xs:element ref="AD"/>
				<xs:element ref="ED"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="name" type="xs:string"/>
	<xs:element name="class" type="xs:NCName"/>
	<xs:element name="race" type="xs:string"/>
	<xs:element name="damage" type="xs:integer"/>
	<xs:element name="health" type="xs:integer"/>
	<xs:element name="skill" type="xs:integer"/>
	<xs:element name="FD" type="xs:integer"/>
	<xs:element name="DD" type="xs:integer"/>
	<xs:element name="AD" type="xs:integer"/>
	<xs:element name="ED" type="xs:integer"/>
</xs:schema>

=== LennartC/CQ2-Sim/src/main/java/be/lacerta/cq2/battlecalc/util/xml/crits.xml
<?xml version="1.0" encoding="UTF-8"?>
<creatures xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="crits.xsd">
	<creature>
		<name>Remnant Overmind</name>
		<class>Air</class>
		<race>Air Remnant</race>
		<damage>140</damage>
		<health>280</health>
		<skill>0</skill>
		<FD>50</FD>
		<DD>50</DD>
		<AD>150</AD>
		<ED>50</ED>
	</creature>
	<creature>
		<name>Air Remnant</name>
		<class>Air</class>
		<race>Air Remnant</race>
		<damage>50</damage>
		<health>100</health>
		<skill>217</skill>
		<FD>50</FD>
		<DD>50</DD>
		<AD>150</AD>
		<ED>50</ED>
	</creature>
	<creature>
		<name>Vapour Remnant</name>
		<class>Air</class>
		<race>Air Remnant</race>
		<damage>80</damage>
		<health>160</health>
		<skill>347</skill>
		<FD>50</FD>
		<DD>50</DD>
		<AD>150</AD>
		<ED>50</ED>
	</creature>
	<creature>
		<name>Goldblight Angel</name>
		<class>Air</class>
		<race>Angel</race>
		<damage>109</damage>
		<health>225</health>
		<skill>310</skill>
		<FD>0</FD>
		<DD>35</DD>
		<AD>100</AD>
		<ED>65</ED>
	</creature>
	<creature>
		<name>Angel Soulslayer</name>
		<class>Air</class>
		<race>Angel</race>
		<damage>189</damage>
		<health>409</health>
		<skill>551</skill>
		<FD>0</FD>
		<DD>35</DD>
		<AD>100</AD>
		<ED>65</ED>
	</creature>
	<creature>
		<name>Weak Angel</name>
		<class>Air</class>
		<race>Angel</race>
		<damage>6</damage>
		<health>13</health>
		<skill>18</skill>
		<FD>0</FD>
		<DD>35</DD>
		<AD>100</AD>
		<ED>65</ED>
	</creature>
	<creature>
		<name>Firewound Angel</name>
		<class>Air</class>
		<race>Angel</race>
		<damage>52</damage>
		<health>83</health>
		<skill>131</skill>
		<FD>0</FD>
		<DD>35</DD>
		<AD>100</AD>
		<ED>65</ED>
	</creature>
	<creature>
		<name>Balrog Overlord</name>
		<class>Air</class>
		<race>Balrog</race>
		<damage>65</damage>
		<health>260</health>
		<skill>420</skill>
		<FD>40</FD>
		<DD>40</DD>
		<AD>150</AD>
		<ED>50</ED>
	</creature>
	<creature>
		<name>Balrog</name>
		<class>Air</class>
		<race>Balrog</race>
		<damage>34</damage>
		<health>55</health>
		<skill>129</skill>
		<FD>40</FD>
		<DD>40</DD>
		<AD>150</AD>
		<ED>50</ED>
	</creature>
	<creature>
		<name>Balrog Devourer</name>
		<class>Air</class>
		<race>Balrog</race>
		<damage>55</damage>
		<health>135</health>
		<skill>261</skill>
		<FD>40</FD>
		<DD>40</DD>
		<AD>150</AD>
		<ED>50</ED>
	</creature>
	<creature>
		<name>Vampire Bat</name>
		<class>Air</class>
		<race>Bat</race>
		<damage>157</damage>
		<health>229</health>
		<skill>532</skill>
		<FD>0</FD>
		<DD>50</DD>
		<AD>100</AD>
		<ED>50</ED>
	</creature>
	<creature>
		<name>Crypt Bat</name>
		<class>Air</class>
		<race>Bat</race>
		<damage>34</damage>
		<health>62</health>
		<skill>130</skill>
		<FD>0</FD>
		<DD>50</DD>
		<AD>100</AD>
		<ED>50</ED>
	</creature>
	<creature>
		<name>Mutated Crypt Bat</name>
		<class>Air</class>
		<race>Bat</race>
		<damage>95</damage>
		<health>162</health>
		<skill>352</skill>
		<FD>0</FD>
		<DD>50</DD>
		<AD>100</AD>
		<ED>50</ED>
	</creature>
	<creature>
		<name>Pulse Bat</name>
		<class>Air</class>
		<race>Bat</race>
		<damage>24</damage>
		<health>44</health>
		<skill>92</skill>
		<FD>0</FD>
		<DD>50</DD>
		<AD>100</AD>
		<ED>50</ED>
	</creature>
	<creature>
		<name>Mutated Pulse Bat</name>
		<class>Air</class>
		<race>Bat</race>
		<damage>71</damage>
		<health>151</health>
		<skill>293</skill>
		<FD>0</FD>
		<DD>50</DD>
		<AD>100</AD>
		<ED>50</ED>
	</creature>
	<creature>
		<name>Night Bat</name>
		<class>Air</class>
		<race>Bat</race>
		<damage>12</damage>
		<health>26</health>
		<skill>50</skill>
		<FD>0</FD>
		<DD>50</DD>
		<AD>100</AD>
		<ED>50</ED>
	</creature>
	<creature>
		<name>Mutated Cave Bat</name>
		<class>Air</class>
		<race>Bat</race>
		<damage>53</damage>
		<health>106</health>
		<skill>212</skill>
		<FD>0</FD>
		<DD>50</DD>
		<AD>100</AD>
		<ED>50</ED>
	</creature>
	<creature>
		<name>Cave Bat</name>
		<class>Air</class>
		<race>Bat</race>
		<damage>3</damage>
		<health>8</health>
		<skill>14</skill>
		<FD>0</FD>
		<DD>50</DD>
		<AD>100</AD>
		<ED>50</ED>
	</creature>
	<creature>
		<name>Dragon Scream</name>
		<class>Air</class>
		<race>Dragon</race>
		<damage>124</damage>
		<health>261</health>
		<skill>520</skill>
		<FD>0</FD>
		<DD>65</DD>
		<AD>100</AD>
		<ED>60</ED>
	</creature>
	<creature>
		<name>Dragon Scout</name>
		<class>Air</class>
		<race>Dragon</race>
		<damage>91</damage>
		<health>181</health>
		<skill>371</skill>
		<FD>0</FD>
		<DD>65</DD>
		<AD>100</AD>
		<ED>60</ED>
	</creature>
	<creature>
		<name>Dragon Revenant</name>
		<class>Air</class>
		<race>Dragon</race>
		<damage>155</damage>
		<health>297</health>
		<skill>582</skill>
		<FD>0</FD>
		<DD>65</DD>
		<AD>100</AD>
		<ED>60</ED>
	</creature>
	<creature>
		<name>Dragon Soldier</name>
		<class>Air</class>
		<race>Dragon</race>
		<damage>122</damage>
		<health>240</health>
		<skill>494</skill>
		<FD>0</FD>
		<DD>65</DD>
		<AD>100</AD>
		<ED>60</ED>
	</creature>
	<creature>
		<name>Dragon Sentry</name>
		<class>Air</class>
		<race>Dragon</race>
		<damage>151</damage>
		<health>273</health>
		<skill>563</skill>
		<FD>0</FD>
		<DD>65</DD>
		<AD>100</AD>
		<ED>60</ED>
	</creature>
	<creature>
		<name>Dragon Guardian</name>
		<class>Air</class>
		<race>Dragon</race>
		<damage>109</damage>
		<health>226</health>
		<skill>453</skill>
		<FD>0</FD>
		<DD>65</DD>
		<AD>100</AD>
		<ED>60</ED>
	</creature>
	<creature>
		<name>Dragon Sentinel</name>
		<class>Air</class>
		<race>Dragon</race>
		<damage>137</damage>
		<health>268</health>
		<skill>542</skill>
		<FD>0</FD>
		<DD>65</DD>
		<AD>100</AD>
		<ED>60</ED>
	</creature>
	<creature>
		<name>Dragon Nymph</name>
		<class>Air</class>
		<race>Dragon</race>
		<damage>103</damage>
		<health>200</health>
		<skill>414</skill>
		<FD>0</FD>
		<DD>65</DD>
		<AD>100</AD>
		<ED>60</ED>
	</creature>
	<creature>
		<name>Dragon Queen</name>
		<class>Air</class>
		<race>Dragon</race>
		<damage>168</damage>
		<health>331</health>
		<skill>613</skill>
		<FD>0</FD>
		<DD>65</DD>
		<AD>100</AD>
		<ED>60</ED>
	</creature>
	<creature>
		<name>Goretongue Gargoyle</name>
		<class>Air</class>
		<race>Gargoyle</race>
		<damage>22</damage>
		<health>57</health>
		<skill>70</skill>
		<FD>0</FD>
		<DD>65</DD>
		<AD>100</AD>
		<ED>30</ED>
	</creature>
	<creature>
		<name>Nightwing Gargoyle</name>
		<class>Air</class>
		<race>Gargoyle</race>
		<damage>79</damage>
		<health>201</health>
		<skill>250</skill>
		<FD>0</FD>
		<DD>65</DD>
		<AD>100</AD>
		<ED>30</ED>
	</creature>
	<creature>
		<name>Bloodclaw Gargoyle</name>
		<class>Air</class>
		<race>Gargoyle</race>
		<damage>151</damage>
		<health>321</health>
		<skill>434</skill>
		<FD>0</FD>
		<DD>65</DD>
		<AD>100</AD>
		<ED>30</ED>
	</creature>
	<creature>
		<name>Pit Wraith Dominator</name>
		<class>Air</class>
		<race>Pit Wraith</race>
		<damage>162</damage>
		<health>209</health>
		<skill>371</skill>
		<FD>0</FD>
		<DD>20</DD>
		<AD>100</AD>
		<ED>70</ED>
	</creature>
	<creature>
		<name>Pit Wraith Titan</name>
		<class>Air</class>
		<race>Pit Wraith</race>
		<damage>194</damage>
		<health>318</health>
		<skill>490</skill>
		<FD>0</FD>
		<DD>20</DD>
		<AD>100</AD>
		<ED>70</ED>
	</creature>
	<creature>
		<name>Pit Wraith Lord</name>
		<class>Air</class>
		<race>Pit Wraith</race>
		<damage>251</damage>
		<health>382</health>
		<skill>614</skill>
		<FD>0</FD>
		<DD>20</DD>
		<AD>100</AD>
		<ED>70</ED>
	</creature>
	<creature>
		<name>Pit Wraith Lurker</name>
		<class>Air</class>
		<race>Pit Wraith</race>
		<damage>82</damage>
		<health>109</health>
		<skill>190</skill>
		<FD>0</FD>
		<DD>20</DD>
		<AD>100</AD>
		<ED>70</ED>
	</creature>
	<creature>
		<name>Ramun Rift Dancer</name>
		<class>Air</class>
		<race>Rift Dancer</race>
		<damage>16</damage>
		<health>29</health>
		<skill>310</skill>
		<FD>0</FD>
		<DD>55</DD>
		<AD>110</AD>
		<ED>55</ED>
	</creature>
	<creature>
		<name>Inaer Rift Dancer</name>
		<class>Air</class>
		<race>Rift Dancer</race>
		<damage>21</damage>
		<health>43</health>
		<skill>432</skill>
		<FD>0</FD>
		<DD>55</DD>
		<AD>110</AD>
		<ED>55</ED>
	</creature>
	<creature>
		<name>Aen Rift Dancer</name>
		<class>Air</class>
		<race>Rift Dancer</race>
		<damage>24</damage>
		<health>49</health>
		<skill>493</skill>
		<FD>0</FD>
		<DD>55</DD>
		<AD>110</AD>
		<ED>55</ED>
	</creature>
	<creature>
		<name>Nadin Rift Dancer</name>
		<class>Air</class>
		<race>Rift Dancer</race>
		<damage>20</damage>
		<health>33</health>
		<skill>371</skill>
		<FD>0</FD>
		<DD>55</DD>
		<AD>110</AD>
		<ED>55</ED>
	</creature>
	<creature>
		<name>Rift Channeler</name>
		<class>Air</class>
		<race>Rift Dancer</race>
		<damage>33</damage>
		<health>55</health>
		<skill>614</skill>
		<FD>0</FD>
		<DD>55</DD>
		<AD>110</AD>
		<ED>55</ED>
	</creature>
	<creature>
		<name>Aerum Rift Dancer</name>
		<class>Air</class>
		<race>Rift Dancer</race>
		<damage>27</damage>
		<health>55</health>
		<skill>554</skill>
		<FD>0</FD>
		<DD>55</DD>
		<AD>110</AD>
		<ED>55</ED>
	</creature>
	<creature>
		<name>Succubus Spirit</name>
		<class>Air</class>
		<race>Spirit</race>
		<damage>153</damage>
		<health>288</health>
		<skill>570</skill>
		<FD>0</FD>
		<DD>35</DD>
		<AD>100</AD>
		<ED>65</ED>
	</creature>
	<creature>
		<name>Ancient Spirit</name>
		<class>Air</class>
		<race>Spirit</race>
		<damage>151</damage>
		<health>354</health>
		<skill>604</skill>
		<FD>0</FD>
		<DD>35</DD>
		<AD>100</AD>
		<ED>65</ED>
	</creature>
	<creature>
		<name>Willow Spirit</name>
